### ISSUE TITLE
Is LDBC possible to test for Neptune?

### ISSUE THREAD

**Issue by RuiRitaYang** [ldbc/ldbc_snb_driver#131]
Hi LDBC group,

Thanks a lot for your fantastic work. I'm new to LDBC and wants to use it to test some graph database for research purpose. I noticed that there are workload implementations for Cyber, PostgreSQL, SPARQL, but it's not clear to me which database it could support now for Database connecter. So I wonder whether there is some information about it.

Also, Neptune is a AWS Web service. Is that by any chance possible that LDBC has a database connecter to it? If not, is there any suggestion if I want to do a personal test with LDBC workload?

At last, I'm not sure whether github issue is the community to discuss ldbc deployment/usage problems. If this is not, do you mind point me where I could look for more information? I could not find the community directly from Google Search.

Thank you so much in advance.

Regards,
-Rui

**Comment by szarnyasg** [comment]
Hello Rui,

Thanks for your interest in LDBC!

The connectors usually rely on the driver provided by the vendors (e.g. the neo4j-java-driver using the Bolt protocol for Neo4j):

* The Postgres one could work with systems that support the Postgres wire protocol and the `WITH RECURSIVE` SQL'99 clause. The former requirement is satisfied by quite a few systems (yugabyteDB, CockroachDB, CrateDB, Materialize etc.) but many systems only support clauses up to SQL'92. Also, it's very likely that the loading scripts (the schema/index definition commands and shell scripts) will need a few tweaks.
* The Cypher implementation works with Neo4j: the one on the `stable` branch supports Neo4j 3.x while the one on the `dev` branch works with 4.x. The `stable` one should be compatible with Memgraph as well but it does not have 100% coverage due to Memgraph's limited Cypher support.
* The SPARQL implementation has been tested with Stardog. It could work with any Sesame-compatible semantic database (BlazeGraph, Virtuoso, GraphDB by Ontotext). I've removed it from the `dev` branch due to the lack of effort to maintain this but it's still on the `stable` branch. If needed, it could be ported to RDF4J, a successor of Sesame, with a reasonable amount of effort.
* As far as I'm aware, there's no publicly available AWS Neptune connector for SNB.

> At last, I'm not sure whether github issue is the community to discuss ldbc deployment/usage problems. If this is not, do you mind point me where I could look for more information? I could not find the community directly from Google Search.

GitHub issues are perfect for these sorts of questions. We also have a Slack, let me know if I shall invite you.

Gabor
