### ISSUE TITLE
how to set operation count

### ISSUE THREAD

**Issue by mpolonioli** [ldbc/ldbc_snb_driver#70]
In file ldbc_driver_default.properties I have to set the value of the parameter operation_count.
I can't figuring out what value should I put. 
Is there a rule to decide or a suggested value?

Thanks

**Comment by ArnauPrat** [comment]
Depending on what you want to do. In principle, a valid run of the benchmark should last, at least 2 hours of simulation time(time in the simulated social network). Thus, you should set the number of operations such that the driver executes those spanning at least 2 hours of simulation, which is hard to tell in advance without looking at the updateStream files. Also, this value will depend on the Scale Factor, since the larger the Scale Factor, the more the number of operations/second in simulation time, thus the larger the operation_count will need to be.

If you are not interested in complying with the official execution rules, just set the value you wish. You can start with 1M operations for warming up and another 1M for execution, and adjust these values as you go.

**Comment by mpolonioli** [comment]
I selected the operation count running the benchmark a few time in order to have a run of at least 2h30m duration.
I set the value at 5k for warmup phase and 17k for run phase using Neo4jDB and an existing implementation of the driver found here: 
https://github.com/PlatformLab/ldbc-snb-impls/tree/master/snb-interactive-neo4j

Thank you
